/**
 * Types of alerts that can be generated by the IoT device layer.
 */
export type AlertType = 'LOW_BATTERY' | 'DEVICE_OFFLINE' | 'UNSCHEDULED_OPEN' | 'COMPARTMENT_EMPTY';
/**
 * Service to dispatch alerts to the system's notification layer.
 * Logs to terminal in dev mode; can be wired to real SMS/Email/Push integrations.
 */
export declare function triggerAlert(type: AlertType, deviceId: string, message: string, metadata?: any): void;
/**
 * Evaluates device battery level and triggers an alert if below 15%.
 */
export declare function evaluateBatteryAlert(deviceId: string, batteryPercent: number): void;
/**
 * Triggers a device offline alert.
 */
export declare function evaluateDeviceOfflineAlert(deviceId: string): void;
/**
 * Checks if a compartment access event (IR or Load-Cell drop) occurred outside of its allowed window.
 * The allowed window is when the state is 'available' or 'unlocked-awaiting-meal'.
 */
export declare function evaluateUnscheduledOpenAlert(deviceId: string, compartmentNumber: number, currentState: string, triggerEvent: string): void;
/**
 * Triggers an empty compartment alert.
 */
export declare function evaluateCompartmentEmptyAlert(deviceId: string, compartmentNumber: number): void;
//# sourceMappingURL=alertService.d.ts.map